#!/usr/bin/env node
/**
 * E2E Functional Tests for Swapboard Frontend
 *
 * Tests actual user interactions and verifies correct behavior.
 * Uses mock data with known values to verify filtering, rendering, and validation.
 *
 * Mock data is generated by mock.js using a seeded PRNG (seed: 12345).
 * With MOCK_CONFIG: orderCount=50, activePercent=40, filledPercent=70
 *
 * On top of that seeded set, mock.js appends two multi-select cohorts —
 * fillCohortSize=18 and cancelCohortSize=30, all open — so the totals below
 * are 50 + 18 + 30 orders, of which 20 + 18 + 30 are open. The cohorts are
 * built from their index rather than the PRNG, so the seeded filled/cancelled
 * split is unchanged.
 *
 * Usage:
 *   node test.js [url]
 *
 * The suite targets the v2 layout and pins ?v=2 on whatever URL it is given
 * unless that URL already carries a ?v= of its own.
 */

const path = require("path");
const fs = require("fs");

/** Protocol version these tests are written against. */
const TEST_VERSION = "2";

// Expected values based on mock.js seeded PRNG output (seed: 12345), plus the
// two appended cohorts. Deterministic, though computed at runtime by mock.js.
const EXPECTED = {
  stats: {
    total: "98",
    active: "68",
    filled: "15",
    cancelled: "15",
  },
  tokens: {
    weth: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
    usdt: "0xdac17f958d2ee523a2206206994597c13d831ec7",
  },
};

/**
 * Pins the protocol version in a test URL.
 *
 * These tests exercise the v2 layout — the select column, the batch controls,
 * the [ETH] toggle — none of which exist in v1. Without an explicit `?v=`,
 * resolveVersion() falls back to DEFAULT_VERSION (1) and the selectors miss.
 * An explicit `?v=` in a supplied URL is left alone, so a caller can still
 * point the suite at v1.
 *
 * @param {string} rawUrl - URL to test, file:// or http://
 * @returns {string} URL carrying a `v` parameter
 */
function withVersion(rawUrl) {
  try {
    const parsed = new URL(rawUrl);
    if (!parsed.searchParams.has("v")) parsed.searchParams.set("v", TEST_VERSION);
    return parsed.toString();
  } catch {
    // Not parseable as a URL (a bare path, say); fall back to string append.
    if (/[?&]v=/.test(rawUrl)) return rawUrl;
    return rawUrl + (rawUrl.includes("?") ? "&" : "?") + "v=" + TEST_VERSION;
  }
}

async function runTests() {
  let puppeteer;
  try {
    puppeteer = require("puppeteer");
  } catch (e) {
    console.error("Puppeteer required. Run: npm install puppeteer");
    process.exit(1);
  }

  const url = withVersion(process.argv[2] || "file://" + path.resolve(__dirname, "index.html"));
  console.log("Testing:", url);
  console.log("");

  const isCI = process.env.CI === "true";
  const browser = await puppeteer.launch({
    headless: "new",
    args: isCI ? ["--no-sandbox", "--disable-setuid-sandbox"] : [],
  });
  const page = await browser.newPage();

  let passed = 0;
  let failed = 0;
  const failures = [];

  function test(name, condition, details) {
    if (condition) {
      console.log(`  PASS: ${name}`);
      passed++;
    } else {
      console.log(`  FAIL: ${name}`);
      if (details) console.log(`        ${details}`);
      failed++;
      failures.push({ name, details });
    }
  }

  async function getOrderIds() {
    // Column 1 is the selection checkbox and column 2 is the action cell, so
    // the trade ID lives in column 3.
    return page.$$eval("#order-table tr", (rows) => {
      return rows
        .map((row) => {
          const idCell = row.querySelector("td:nth-child(3)");
          return idCell ? idCell.textContent.trim() : null;
        })
        .filter((id) => id !== null && id !== "" && id !== "No orders found");
    });
  }

  async function getRowCount() {
    const ids = await getOrderIds();
    return ids.length;
  }

  async function clickRadio(value) {
    await page.click(`input[name="status"][value="${value}"]`);

    // Wait for orders to load (not loading, not empty, has real data)
    await page.waitForFunction(
      () => {
        const rows = document.querySelectorAll("#order-table tr");
        if (rows.length === 0) return false;
        // Match on the whole row: the first cell is now the selection
        // checkbox, whose text is always empty.
        const text = rows[0].textContent || "";
        // Wait until we have real data (not loading, not "no orders")
        return !text.includes("Loading") && !text.includes("No orders");
      },
      { timeout: 5000 }
    );
    // Extra delay to ensure data is fully rendered
    await new Promise((r) => setTimeout(r, 400));
  }

  async function selectToken(selectId, tokenAddress) {
    await page.select(selectId, tokenAddress);
    await page.waitForFunction(
      () => !document.querySelector("#order-table tr")?.textContent.includes("Loading"),
      { timeout: 3000 }
    );
    // Extra delay to ensure data is rendered
    await new Promise((r) => setTimeout(r, 300));
  }

  try {
    // Inject mock before page loads
    const mockScript = fs.readFileSync(path.resolve(__dirname, "mock.js"), "utf8");
    await page.evaluateOnNewDocument(mockScript);

    await page.goto(url, { waitUntil: "domcontentloaded", timeout: 10000 });

    // Wait for initial data load
    await page.waitForFunction(() => document.getElementById("stat-total")?.textContent !== "--", {
      timeout: 5000,
    });

    // ==================== STATS TESTS ====================
    console.log("--- Stats Rendering ---");

    const statTotal = await page.$eval("#stat-total", (el) => el.textContent);
    test(
      "Total orders matches mock data",
      statTotal === EXPECTED.stats.total,
      `Expected "${EXPECTED.stats.total}", got "${statTotal}"`
    );

    const statActive = await page.$eval("#stat-active", (el) => el.textContent);
    test(
      "Active orders matches mock data",
      statActive === EXPECTED.stats.active,
      `Expected "${EXPECTED.stats.active}", got "${statActive}"`
    );

    const statFilled = await page.$eval("#stat-filled", (el) => el.textContent);
    test(
      "Filled orders matches mock data",
      statFilled === EXPECTED.stats.filled,
      `Expected "${EXPECTED.stats.filled}", got "${statFilled}"`
    );

    const statCancelled = await page.$eval("#stat-cancelled", (el) => el.textContent);
    test(
      "Cancelled orders matches mock data",
      statCancelled === EXPECTED.stats.cancelled,
      `Expected "${EXPECTED.stats.cancelled}", got "${statCancelled}"`
    );

    // ==================== STATUS FILTER TESTS ====================
    console.log("\n--- Status Filter Behavior ---");

    // Wait for orders to load (after stats, orders + prices take longer)
    await page.waitForFunction(
      () => {
        const rows = document.querySelectorAll("#order-table tr");
        const firstCell = rows[0]?.querySelector("td");
        return (
          rows.length > 0 &&
          !firstCell?.textContent?.includes("Loading") &&
          !firstCell?.textContent?.includes("No orders")
        );
      },
      { timeout: 5000 }
    );
    await new Promise((r) => setTimeout(r, 300));

    // Default should be "open" - expect 20 active orders (40% of 50)
    let orderIds = await getOrderIds();
    const expectedActive = parseInt(EXPECTED.stats.active);
    test(
      "Default filter shows open orders only",
      orderIds.length === expectedActive,
      `Expected ${expectedActive} orders, got ${orderIds.length}`
    );

    // Switch to "all" filter - PAGE_SIZE (200) exceeds total, so all 50 orders show
    await clickRadio("all");
    orderIds = await getOrderIds();
    const expectedTotal = parseInt(EXPECTED.stats.total);
    test(
      "All filter shows orders (paginated)",
      orderIds.length === expectedTotal,
      `Expected ${expectedTotal} orders, got ${orderIds.length}`
    );

    // Switch to "filled" filter - expect 15 filled orders
    await clickRadio("filled");
    orderIds = await getOrderIds();
    const expectedFilled = parseInt(EXPECTED.stats.filled);
    test(
      "Filled filter shows filled orders",
      orderIds.length === expectedFilled,
      `Expected ${expectedFilled} orders, got ${orderIds.length}`
    );

    // Switch to "cancelled" filter - expect 15 cancelled orders
    await clickRadio("cancelled");
    orderIds = await getOrderIds();
    const expectedCancelled = parseInt(EXPECTED.stats.cancelled);
    test(
      "Cancelled filter shows cancelled orders",
      orderIds.length === expectedCancelled,
      `Expected ${expectedCancelled} orders, got ${orderIds.length}`
    );

    // Reset to open
    await clickRadio("open");
    orderIds = await getOrderIds();

    // ==================== TOKEN FILTER TESTS ====================
    console.log("\n--- Token Filter Behavior ---");

    // Verify token dropdowns are populated
    const sellingOptions = await page.$$eval("#filter-selling option", (opts) =>
      opts.map((o) => o.textContent)
    );
    test(
      "Offered filter has token options",
      sellingOptions.length > 1,
      `Expected multiple options, got ${sellingOptions.length}`
    );

    test(
      "Offered filter includes WETH",
      sellingOptions.includes("WETH"),
      `Options: ${sellingOptions.join(", ")}`
    );

    // Filter by WETH as offered token - should reduce results
    const beforeWethFilter = orderIds.length;
    await selectToken("#filter-selling", EXPECTED.tokens.weth);
    orderIds = await getOrderIds();
    test(
      "WETH offered filter reduces results",
      orderIds.length < beforeWethFilter && orderIds.length > 0,
      `Before: ${beforeWethFilter}, After: ${orderIds.length}`
    );

    // Reset offered filter
    await selectToken("#filter-selling", "");
    orderIds = await getOrderIds();

    // Filter by USDT as wanting token - should reduce results
    const beforeUsdtFilter = orderIds.length;
    await selectToken("#filter-wanting", EXPECTED.tokens.usdt);
    orderIds = await getOrderIds();
    test(
      "USDT wanting filter reduces results",
      orderIds.length < beforeUsdtFilter && orderIds.length > 0,
      `Before: ${beforeUsdtFilter}, After: ${orderIds.length}`
    );

    // Combined filter: WETH offered + USDT wanted - should further reduce
    const beforeCombinedFilter = orderIds.length;
    await selectToken("#filter-selling", EXPECTED.tokens.weth);
    orderIds = await getOrderIds();
    test(
      "Combined filter reduces or maintains results",
      orderIds.length <= beforeCombinedFilter,
      `Before: ${beforeCombinedFilter}, After: ${orderIds.length}`
    );

    // Reset filters
    await selectToken("#filter-selling", "");
    await selectToken("#filter-wanting", "");

    // ==================== ORDER DATA ACCURACY ====================
    console.log("\n--- Order Data Accuracy ---");

    // Verify first row has valid data structure
    // Column order: [0] Select, [1] Fill/Cancel btn, [2] Trade ID, [3] Maker,
    // [4] Offered Token, [5] Offered Size, [6] Wanted Token, [7] Wanted Size,
    // [8] USD Val, [9] Price
    const firstRow = await page.$$eval("#order-table tr:first-child td", (cells) =>
      cells.map((c) => c.textContent.trim())
    );

    // Trade ID column now includes share button, extract just the number
    const tradeIdMatch = firstRow[2].match(/^(\d+)/);
    test(
      "First order has numeric ID",
      tradeIdMatch !== null,
      `Expected numeric ID, got "${firstRow[2]}"`
    );

    test(
      "First order has valid offered token symbol",
      firstRow[4] && firstRow[4].length > 0 && firstRow[4] !== "undefined",
      `Got "${firstRow[4]}"`
    );

    test(
      "First order has valid wanting token symbol",
      firstRow[6] && firstRow[6].length > 0 && firstRow[6] !== "undefined",
      `Got "${firstRow[6]}"`
    );

    // Verify amount starts with a formatted number. A partially filled v2
    // order appends an "of <original> left" hint after it.
    test(
      "First order offered amount is formatted number",
      /^[\d,]+\.?\d*/.test(firstRow[5]),
      `Got "${firstRow[5]}"`
    );

    // ==================== TABLE STRUCTURE ====================
    console.log("\n--- Table Structure ---");

    const columnCount = await page.$$eval(
      "#order-table tr:first-child td",
      (cells) => cells.length
    );
    test(
      "Order table has 10 columns",
      columnCount === 10,
      `Expected 10 columns, got ${columnCount}`
    );

    const headers = await page.$$eval("thead th", (ths) => ths.map((t) => t.textContent.trim()));
    test(
      "Table headers are correct",
      headers.length === 10 &&
        headers[2].includes("Trade ID") &&
        headers[3].includes("Maker") &&
        headers[4].includes("Offered"),
      `Got headers: ${headers.join(", ")}`
    );

    // ==================== V2: MULTI-SELECT ====================
    console.log("\n--- V2 Multi-select ---");

    const rowCount = await page.$$eval("#order-table tr", (rows) => rows.length);
    const checkboxCount = await page.$$eval(
      "#order-table td.select-col input[type=checkbox]",
      (boxes) => boxes.length
    );
    test(
      "Every order row has a selection checkbox",
      checkboxCount === rowCount,
      `Expected ${rowCount} checkboxes, got ${checkboxCount}`
    );

    const barHiddenBefore = await page.$eval("#selection-bar", (el) =>
      el.classList.contains("hidden")
    );
    test("Selection bar is hidden with nothing selected", barHiddenBefore === true);

    await page.click("#order-table tr:first-child td.select-col input[type=checkbox]");
    await new Promise((r) => setTimeout(r, 200));

    const selectionState = await page.evaluate(() => ({
      hidden: document.querySelector("#selection-bar").classList.contains("hidden"),
      count: document.querySelector("#selection-count").textContent,
      fillHidden: document.querySelector("#batch-fill-btn").classList.contains("hidden"),
    }));
    test(
      "Selecting an order reveals [Fill All]",
      selectionState.hidden === false &&
        selectionState.count.startsWith("1 order") &&
        selectionState.fillHidden === false,
      `Got ${JSON.stringify(selectionState)}`
    );

    await page.click("#selection-clear");
    await new Promise((r) => setTimeout(r, 200));
    const barHiddenAfter = await page.$eval("#selection-bar", (el) =>
      el.classList.contains("hidden")
    );
    test("[Clear] empties the selection", barHiddenAfter === true);

    // ==================== V2: BATCH CREATE ====================
    console.log("\n--- V2 Batch create ---");

    // The Sell Tokens button only appears once a wallet is connected, so open
    // the modal directly to exercise the form.
    await page.evaluate(() => document.querySelector("#sell-modal").classList.remove("hidden"));

    const createRowCount = await page.$$eval("#create-rows .create-row", (rows) => rows.length);
    test(
      "Sell Tokens form starts with one order row",
      createRowCount === 1,
      `Got ${createRowCount}`
    );

    await page.click("#add-sell-btn");
    await new Promise((r) => setTimeout(r, 100));
    const afterAdd = await page.$$eval("#create-rows .create-row", (rows) => rows.length);
    test("[Add Sell] appends an order row", afterAdd === 2, `Got ${afterAdd}`);

    await page.click("#create-rows .create-row:last-child .create-row-remove");
    await new Promise((r) => setTimeout(r, 100));
    const afterRemove = await page.$$eval("#create-rows .create-row", (rows) => rows.length);
    test("Row [x] removes an order row", afterRemove === 1, `Got ${afterRemove}`);

    // Native ETH selection pins the address field to the sentinel and locks it
    await page.click('#create-rows .create-row [data-eth-for="tokenA"]');
    await new Promise((r) => setTimeout(r, 100));
    const ethField = await page.$eval('#create-rows .create-row [data-field="tokenA"]', (el) => ({
      value: el.value,
      readOnly: el.readOnly,
    }));
    test(
      "[ETH] selects native ETH and locks the address field",
      ethField.value.toLowerCase() === "0x" + "e".repeat(40) && ethField.readOnly === true,
      `Got ${JSON.stringify(ethField)}`
    );
  } catch (e) {
    console.error("\nTest execution error:", e.message);
    failed++;
    failures.push({ name: "Test execution", details: e.message });
  }

  await browser.close();

  // Summary
  console.log("\n========================================");
  console.log(`Results: ${passed} passed, ${failed} failed`);
  console.log("========================================");

  if (failures.length > 0) {
    console.log("\nFailure details:");
    failures.forEach((f, i) => {
      console.log(`  ${i + 1}. ${f.name}`);
      if (f.details) console.log(`     ${f.details}`);
    });
  }

  console.log("");
  process.exit(failed > 0 ? 1 : 0);
}

runTests();
