#!/usr/bin/env node
/**
 * E2E Functional Tests for Swapboard Frontend
 *
 * Tests actual user interactions and verifies correct behavior.
 * Uses mock data with known values to verify filtering, rendering, and validation.
 *
 * Mock data is generated by mock.js using a seeded PRNG (seed: 12345).
 * With MOCK_CONFIG: orderCount=50, activePercent=40, filledPercent=70
 *
 * Usage:
 *   node test.js [url]
 */

const path = require("path");
const fs = require("fs");

// Expected values based on mock.js seeded PRNG output (seed: 12345)
// These are dynamically calculated by mock.js but deterministic
const EXPECTED = {
  stats: {
    total: "50",
    active: "20",
    filled: "15",
    cancelled: "15"
  },
  tokens: {
    weth: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
    usdt: "0xdac17f958d2ee523a2206206994597c13d831ec7"
  }
};

async function runTests() {
  let puppeteer;
  try {
    puppeteer = require("puppeteer");
  } catch (e) {
    console.error("Puppeteer required. Run: npm install puppeteer");
    process.exit(1);
  }

  const url = process.argv[2] || "file://" + path.resolve(__dirname, "index.html");
  console.log("Testing:", url);
  console.log("");

  const isCI = process.env.CI === "true";
  const browser = await puppeteer.launch({
    headless: "new",
    args: isCI ? ["--no-sandbox", "--disable-setuid-sandbox"] : []
  });
  const page = await browser.newPage();

  const errors = [];
  page.on("pageerror", err => errors.push(err.message));

  let passed = 0;
  let failed = 0;
  const failures = [];

  function test(name, condition, details) {
    if (condition) {
      console.log(`  PASS: ${name}`);
      passed++;
    } else {
      console.log(`  FAIL: ${name}`);
      if (details) console.log(`        ${details}`);
      failed++;
      failures.push({ name, details });
    }
  }

  async function getOrderIds() {
    return page.$$eval("#order-table tr", rows => {
      return rows.map(row => {
        const firstCell = row.querySelector("td:first-child");
        return firstCell ? firstCell.textContent.trim() : null;
      }).filter(id => id !== null && id !== "No orders found");
    });
  }

  async function getRowCount() {
    const ids = await getOrderIds();
    return ids.length;
  }

  async function clickRadio(value) {
    // Get current row count before clicking
    const prevCount = await page.$$eval("#order-table tr", rows => rows.length);

    await page.click(`input[name="status"][value="${value}"]`);

    // Wait for loading or row count change
    await page.waitForFunction(
      (prev) => {
        const firstCell = document.querySelector("#order-table tr td");
        const isLoading = firstCell?.textContent?.includes("Loading");
        const currentCount = document.querySelectorAll("#order-table tr").length;
        // Wait until not loading AND (count changed OR we've settled)
        return !isLoading;
      },
      { timeout: 3000 },
      prevCount
    );
    // Extra delay to ensure data is rendered
    await new Promise(r => setTimeout(r, 300));
  }

  async function selectToken(selectId, tokenAddress) {
    await page.select(selectId, tokenAddress);
    await page.waitForFunction(
      () => !document.querySelector("#order-table tr td")?.textContent.includes("Loading"),
      { timeout: 3000 }
    );
    // Extra delay to ensure data is rendered
    await new Promise(r => setTimeout(r, 300));
  }

  try {
    // Inject mock before page loads
    const mockScript = fs.readFileSync(path.resolve(__dirname, "mock.js"), "utf8");
    await page.evaluateOnNewDocument(mockScript);

    await page.goto(url, { waitUntil: "domcontentloaded", timeout: 10000 });

    // Wait for initial data load
    await page.waitForFunction(
      () => document.getElementById("stat-total")?.textContent !== "--",
      { timeout: 5000 }
    );

    // ==================== STATS TESTS ====================
    console.log("--- Stats Rendering ---");

    const statTotal = await page.$eval("#stat-total", el => el.textContent);
    test(
      "Total orders matches mock data",
      statTotal === EXPECTED.stats.total,
      `Expected "${EXPECTED.stats.total}", got "${statTotal}"`
    );

    const statActive = await page.$eval("#stat-active", el => el.textContent);
    test(
      "Active orders matches mock data",
      statActive === EXPECTED.stats.active,
      `Expected "${EXPECTED.stats.active}", got "${statActive}"`
    );

    const statFilled = await page.$eval("#stat-filled", el => el.textContent);
    test(
      "Filled orders matches mock data",
      statFilled === EXPECTED.stats.filled,
      `Expected "${EXPECTED.stats.filled}", got "${statFilled}"`
    );

    const statCancelled = await page.$eval("#stat-cancelled", el => el.textContent);
    test(
      "Cancelled orders matches mock data",
      statCancelled === EXPECTED.stats.cancelled,
      `Expected "${EXPECTED.stats.cancelled}", got "${statCancelled}"`
    );

    // ==================== STATUS FILTER TESTS ====================
    console.log("\n--- Status Filter Behavior ---");

    // Default should be "open" - expect 20 active orders (40% of 50)
    let orderIds = await getOrderIds();
    const expectedActive = parseInt(EXPECTED.stats.active);
    test(
      "Default filter shows open orders only",
      orderIds.length === expectedActive,
      `Expected ${expectedActive} orders, got ${orderIds.length}`
    );

    // Switch to "all" filter - expect all 50 orders (paginated to 20)
    await clickRadio("all");
    orderIds = await getOrderIds();
    test(
      "All filter shows orders (paginated)",
      orderIds.length === 20,
      `Expected 20 orders (page size), got ${orderIds.length}`
    );

    // Switch to "filled" filter - expect 15 filled orders
    await clickRadio("filled");
    orderIds = await getOrderIds();
    const expectedFilled = parseInt(EXPECTED.stats.filled);
    test(
      "Filled filter shows filled orders",
      orderIds.length === expectedFilled,
      `Expected ${expectedFilled} orders, got ${orderIds.length}`
    );

    // Switch to "cancelled" filter - expect 15 cancelled orders
    await clickRadio("cancelled");
    orderIds = await getOrderIds();
    const expectedCancelled = parseInt(EXPECTED.stats.cancelled);
    test(
      "Cancelled filter shows cancelled orders",
      orderIds.length === expectedCancelled,
      `Expected ${expectedCancelled} orders, got ${orderIds.length}`
    );

    // Reset to open
    await clickRadio("open");
    orderIds = await getOrderIds();

    // ==================== TOKEN FILTER TESTS ====================
    console.log("\n--- Token Filter Behavior ---");

    // Verify token dropdowns are populated
    const sellingOptions = await page.$$eval("#filter-selling option", opts =>
      opts.map(o => o.textContent)
    );
    test(
      "Selling filter has token options",
      sellingOptions.length > 1,
      `Expected multiple options, got ${sellingOptions.length}`
    );

    test(
      "Selling filter includes WETH",
      sellingOptions.includes("WETH"),
      `Options: ${sellingOptions.join(", ")}`
    );

    // Filter by WETH as selling token - should reduce results
    const beforeWethFilter = orderIds.length;
    await selectToken("#filter-selling", EXPECTED.tokens.weth);
    orderIds = await getOrderIds();
    test(
      "WETH selling filter reduces results",
      orderIds.length < beforeWethFilter && orderIds.length > 0,
      `Before: ${beforeWethFilter}, After: ${orderIds.length}`
    );

    // Reset selling filter
    await selectToken("#filter-selling", "");
    orderIds = await getOrderIds();

    // Filter by USDT as wanting token - should reduce results
    const beforeUsdtFilter = orderIds.length;
    await selectToken("#filter-wanting", EXPECTED.tokens.usdt);
    orderIds = await getOrderIds();
    test(
      "USDT wanting filter reduces results",
      orderIds.length < beforeUsdtFilter && orderIds.length > 0,
      `Before: ${beforeUsdtFilter}, After: ${orderIds.length}`
    );

    // Combined filter: WETH selling + USDT wanting - should further reduce
    const beforeCombinedFilter = orderIds.length;
    await selectToken("#filter-selling", EXPECTED.tokens.weth);
    orderIds = await getOrderIds();
    test(
      "Combined filter reduces or maintains results",
      orderIds.length <= beforeCombinedFilter,
      `Before: ${beforeCombinedFilter}, After: ${orderIds.length}`
    );

    // Reset filters
    await selectToken("#filter-selling", "");
    await selectToken("#filter-wanting", "");

    // ==================== ORDER DATA ACCURACY ====================
    console.log("\n--- Order Data Accuracy ---");

    // Verify first row has valid data structure
    const firstRow = await page.$$eval("#order-table tr:first-child td", cells =>
      cells.map(c => c.textContent.trim())
    );

    test(
      "First order has numeric ID",
      /^\d+$/.test(firstRow[0]),
      `Expected numeric ID, got "${firstRow[0]}"`
    );

    test(
      "First order has valid selling token symbol",
      firstRow[2] && firstRow[2].length > 0 && firstRow[2] !== "undefined",
      `Got "${firstRow[2]}"`
    );

    test(
      "First order has valid wanting token symbol",
      firstRow[4] && firstRow[4].length > 0 && firstRow[4] !== "undefined",
      `Got "${firstRow[4]}"`
    );

    // Verify amount is formatted (contains numbers and possibly commas/decimals)
    test(
      "First order sell amount is formatted number",
      /^[\d,]+\.?\d*$/.test(firstRow[3]),
      `Got "${firstRow[3]}"`
    );

    // ==================== TOKEN INPUT VALIDATION ====================
    console.log("\n--- Token Input Validation ---");

    // Enter invalid address
    await page.type("#create-tokenA", "0xinvalid");
    await new Promise(r => setTimeout(r, 600)); // Wait for debounce

    const tokenAInfo = await page.$eval("#tokenA-info", el => el.textContent);
    test(
      "Invalid address shows error",
      tokenAInfo === "Invalid address",
      `Expected "Invalid address", got "${tokenAInfo}"`
    );

    // Clear and enter valid format (won't fetch real data but validates format)
    await page.$eval("#create-tokenA", el => el.value = "");
    await page.type("#create-tokenA", "0x1234567890123456789012345678901234567890");
    await new Promise(r => setTimeout(r, 600));

    const tokenAInfoValid = await page.$eval("#tokenA-info", el => el.textContent);
    test(
      "Valid address format shows loading/result",
      tokenAInfoValid !== "Invalid address" && tokenAInfoValid !== "",
      `Got "${tokenAInfoValid}"`
    );

    // ==================== TABLE STRUCTURE ====================
    console.log("\n--- Table Structure ---");

    const columnCount = await page.$$eval(
      "#order-table tr:first-child td",
      cells => cells.length
    );
    test(
      "Order table has 8 columns",
      columnCount === 8,
      `Expected 8 columns, got ${columnCount}`
    );

    const headers = await page.$$eval("thead th", ths => ths.map(t => t.textContent.trim()));
    const expectedHeaders = ["Trade ID", "Account", "Selling Token", "Sell Size", "Wanted Token", "Wanted Size", "USD Val", "Price"];
    test(
      "Table headers are correct",
      headers.length === 8 && headers[0].includes("Trade ID") && headers[2].includes("Selling"),
      `Got headers: ${headers.join(", ")}`
    );

    // ==================== ERROR CHECK ====================
    console.log("\n--- Console Errors ---");
    test(
      "No JavaScript errors on page",
      errors.length === 0,
      errors.length > 0 ? `Errors: ${errors.join("; ")}` : undefined
    );

  } catch (e) {
    console.error("\nTest execution error:", e.message);
    failed++;
    failures.push({ name: "Test execution", details: e.message });
  }

  await browser.close();

  // Summary
  console.log("\n========================================");
  console.log(`Results: ${passed} passed, ${failed} failed`);
  console.log("========================================");

  if (failures.length > 0) {
    console.log("\nFailure details:");
    failures.forEach((f, i) => {
      console.log(`  ${i + 1}. ${f.name}`);
      if (f.details) console.log(`     ${f.details}`);
    });
  }

  console.log("");
  process.exit(failed > 0 ? 1 : 0);
}

runTests();
